### ISSUE TITLE
Consider rationalising EquipmentOrSystemTypeEnum with DeviceTypeEnum (Bugzilla Bug 422)

### ISSUE THREAD

**Issue by datexii** [DATEX-II-EU/DatexII#422]
This issue was created automatically with bugzilla2github.py
# Bugzilla Bug 422
Date: 2022-11-16T14:59:17+01:00
From: @iancornwellmottmac
To:   Bard de Vries &lt;<b.devries@u-trex.nl>&gt;

Last updated: 2023-12-18T09:24:28+01:00

**Comment by iancornwellmottmac** [comment]
Despite the suggestion from 18/12/23, I am unsure of whether you would ever want to talk about something as specific as a device in a SituationPublication? Even if so, it might not be worth any semantic distinction from a system fault in a SituationPublication. We can justify that the DeviceType is overlapping but different from EquipmentOrSystemType because they are designed for different use cases.

**Comment by iancornwellmottmac** [comment]
I've added a UML comment to EquipmentOrSystemFault to explain the relation to FaultAndStatus.
